name: CI Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [backend, frontend]
    steps:
      - uses: actions/checkout@v4
      - name: Install and test
        working-directory: ${{ matrix.dir }}
        run: |
          npm ci
          npm run lint --if-present
          npm run build --if-present
          npm test --if-present
